import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    "react/index": "src/react/index.ts",
    "preact/index": "src/preact/index.ts",
    "styles/index": "src/styles/index.ts",
    "server/index": "src/server/index.ts",
    "testing/index": "src/testing/index.ts",
    "tailwind/index": "src/tailwind/index.ts",
    "vue/index": "src/vue/index.ts",
    "svelte/index": "src/svelte/index.ts",
    "qwik/index": "src/qwik/index.ts",
    "solid/index": "src/solid/index.ts",
    "angular/index": "src/angular/index.ts",
    "lit/index": "src/lit/index.ts",
  },
  format: ["esm", "cjs"],
  dts: true,
  sourcemap: true,
  clean: true,
  splitting: true,
  treeshake: true,
  target: "es2020",
  external: [
    "@angular/common",
    "@angular/core",
    "@angular/core/rxjs-interop",
    "lit",
    "preact",
    "preact/hooks",
    "react",
    "react-dom",
    "rxjs",
    "solid-js",
    "solid-js/web",
    "svelte",
    "svelte/store",
    "vue",
    "@builder.io/qwik",
  ],
});
